all:
  hosts:
    server-1:
      ansible_host: 192.168.1.10
      ansible_port: 22
      ansible_user: root
      ansible_ssh_private_key_file: /home/nouhassi/.ssh/id_rsa
    server-2:
      ansible_host: 192.168.1.11
      ansible_port: 22
      ansible_user: admin
      ansible_ssh_private_key_file: /home/nouhassi/.ssh/id_rsa
