- name: Group 1
  hosts: all
  gather_facts: false
  tasks:
  - name: '[manual] Uptime Check'
    shell: uptime
    tags:
    - Afficher uptime
  - name: "[manual] Commande personnalis\xE9e"
    shell: df -h
  - name: '[config:3] Echo'
    shell: echo Hello
    tags:
    - afficher hello
  - name: '[template:1] Install Nginx - installer proprement'
    shell: apt install nginx -y
    tags:
    - Installer nginx
  - name: '[template:1] Start Nginx - demarrer le service'
    shell: systemctl start nginx
    tags:
    - Demarrer nginx
